# Generated by Django 5.2 on 2026-04-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('reports_count', models.IntegerField(default=0)),
                ('last_reported', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('reports_count', models.IntegerField(default=0)),
                ('last_reported', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('SMS', 'SMS Message'), ('EMAIL', 'Email'), ('URL', 'Website Link'), ('PHONE', 'Phone Number')], max_length=10)),
                ('content', models.TextField()),
                ('risk_score', models.IntegerField()),
                ('risk_level', models.CharField(max_length=20)),
                ('reported_by', models.CharField(blank=True, max_length=100, null=True)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrlRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('domain', models.CharField(max_length=255)),
                ('risk_score', models.IntegerField(default=0)),
                ('reports_count', models.IntegerField(default=0)),
                ('is_phishing', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
