# Generated by Django 5.2 on 2026-04-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenshotReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=500)),
                ('extracted_text', models.TextField()),
                ('risk_score', models.IntegerField()),
                ('risk_level', models.CharField(max_length=20)),
                ('has_fake_mpesa', models.BooleanField(default=False)),
                ('detected_amount', models.CharField(blank=True, max_length=50)),
                ('detected_number', models.CharField(blank=True, max_length=50)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
