# Generated by Django 5.2 on 2026-04-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_screenshotreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scamreport',
            name='report_type',
            field=models.CharField(choices=[('SMS', 'SMS Message'), ('EMAIL', 'Email'), ('URL', 'Website Link'), ('PHONE', 'Phone Number'), ('WHATSAPP', 'WhatsApp Chat')], max_length=20),
        ),
    ]
