# Generated by Django 5.2 on 2026-04-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_alter_scamreport_report_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('risk_score', models.IntegerField(default=0)),
                ('reports_count', models.IntegerField(default=0)),
                ('scam_patterns_detected', models.TextField(blank=True)),
                ('last_message_preview', models.CharField(blank=True, max_length=200)),
                ('first_reported', models.DateTimeField(auto_now_add=True)),
                ('last_reported', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Risk',
                'verbose_name_plural': 'WhatsApp Risks',
                'ordering': ['-risk_score', '-reports_count'],
            },
        ),
        migrations.AlterModelOptions(
            name='emailrisk',
            options={'ordering': ['-risk_score', '-reports_count'], 'verbose_name': 'Email Risk', 'verbose_name_plural': 'Email Risks'},
        ),
        migrations.AlterModelOptions(
            name='phonerisk',
            options={'ordering': ['-risk_score', '-reports_count'], 'verbose_name': 'Phone Risk', 'verbose_name_plural': 'Phone Risks'},
        ),
        migrations.AlterModelOptions(
            name='scamreport',
            options={'ordering': ['-date_reported'], 'verbose_name': 'Scam Report', 'verbose_name_plural': 'Scam Reports'},
        ),
        migrations.AlterModelOptions(
            name='screenshotreport',
            options={'ordering': ['-date_reported'], 'verbose_name': 'Screenshot Report', 'verbose_name_plural': 'Screenshot Reports'},
        ),
        migrations.AlterModelOptions(
            name='urlrisk',
            options={'ordering': ['-risk_score', '-date_added'], 'verbose_name': 'URL Risk', 'verbose_name_plural': 'URL Risks'},
        ),
    ]
