# Generated by Django 5.2 on 2026-04-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_whatsapprisk_alter_emailrisk_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scamreport',
            name='report_type',
            field=models.CharField(choices=[('SMS', 'SMS Message'), ('EMAIL', 'Email'), ('URL', 'Website Link'), ('PHONE', 'Phone Number'), ('WHATSAPP', 'WhatsApp Chat'), ('SCREENSHOT', 'Screenshot'), ('CALL', 'Phone Call')], max_length=20),
        ),
    ]
