# Generated by Django 5.2 on 2026-05-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0005_alter_scamreport_report_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=15, unique=True)),
                ('report_count', models.IntegerField(default=1)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('first_reported', models.DateTimeField(auto_now_add=True)),
                ('last_reported', models.DateTimeField(auto_now=True)),
                ('reported_by', models.CharField(blank=True, help_text='IPs or user IDs', max_length=500)),
                ('scam_category', models.CharField(blank=True, help_text='e.g., M-Pesa, Bank, Insurance', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('CONFIRMED', 'Confirmed Scam'), ('REJECTED', 'Not a Scam'), ('BLOCKED', 'Auto-Blocked')], default='PENDING', max_length=10)),
                ('auto_blocked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-report_count', '-confidence_score'],
            },
        ),
    ]
