# Generated by Django 6.0.4 on 2026-05-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0007_scamreport_user_company_scamreport_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scamreport',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
