# Generated by Django 6.0.4 on 2026-05-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0009_badge_userpoints_userbadge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonatedBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('official_domain', models.CharField(max_length=255)),
                ('notification_email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TakedownProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abuse_email', models.EmailField(max_length=254)),
                ('abuse_url', models.URLField(blank=True)),
                ('success_rate', models.FloatField(default=0.0)),
                ('avg_response_time', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TakedownReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('domain', models.CharField(max_length=255)),
                ('hosting_provider', models.CharField(blank=True, max_length=255)),
                ('scam_type', models.CharField(blank=True, max_length=100)),
                ('reported_by', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('SUBMITTED', 'Submitted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Takedown Successful'), ('FAILED', 'Takedown Failed'), ('REJECTED', 'Rejected by Provider')], default='PENDING', max_length=20)),
                ('google_reported', models.BooleanField(default=False)),
                ('hosting_reported', models.BooleanField(default=False)),
                ('brand_notified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
