# Generated by Django 6.0.4 on 2026-05-14 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0010_impersonatedbrand_takedownprovider_takedownreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('FREE', 'Free Trial'), ('BASIC', 'Basic - Ksh 5,000/mo'), ('PRO', 'Professional - Ksh 15,000/mo'), ('ENTERPRISE', 'Enterprise - Custom')], default='FREE', max_length=20)),
                ('max_employees', models.IntegerField(default=10)),
                ('bulk_verifications', models.IntegerField(default=0)),
                ('bulk_verification_limit', models.IntegerField(default=100)),
                ('api_key', models.CharField(blank=True, max_length=100, unique=True)),
                ('widget_enabled', models.BooleanField(default=False)),
                ('phishing_simulations', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('trial_ends', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='detector.company')),
            ],
        ),
        migrations.CreateModel(
            name='BulkVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_numbers', models.IntegerField(default=0)),
                ('processed', models.IntegerField(default=0)),
                ('scam_found', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('result_file', models.FileField(blank=True, upload_to='bulk_results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('corporate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detector.corporateaccount')),
            ],
        ),
        migrations.CreateModel(
            name='PhishingSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200)),
                ('target_employees', models.IntegerField(default=0)),
                ('clicked_count', models.IntegerField(default=0)),
                ('reported_count', models.IntegerField(default=0)),
                ('ignored_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corporate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detector.corporateaccount')),
            ],
        ),
    ]
