# Generated by Django 6.0.4 on 2026-06-13 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0011_corporateaccount_bulkverification_phishingsimulation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scamreport',
            name='report_type',
            field=models.CharField(choices=[('SMS', 'SMS Message'), ('EMAIL', 'Email'), ('URL', 'Website Link'), ('PHONE', 'Phone Number'), ('WHATSAPP', 'WhatsApp Chat'), ('SCREENSHOT', 'Screenshot'), ('CALL', 'Phone Call'), ('TELEGRAM', 'Telegram Message'), ('USSD', 'USSD Report'), ('WEB', 'Web Page')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='blockednumber',
            index=models.Index(fields=['phone_number'], name='idx_block_phone'),
        ),
        migrations.AddIndex(
            model_name='blockednumber',
            index=models.Index(fields=['status'], name='idx_block_status'),
        ),
        migrations.AddIndex(
            model_name='blockednumber',
            index=models.Index(fields=['confidence_score'], name='idx_block_conf'),
        ),
        migrations.AddIndex(
            model_name='corporateaccount',
            index=models.Index(fields=['api_key'], name='idx_corp_apikey'),
        ),
        migrations.AddIndex(
            model_name='emailrisk',
            index=models.Index(fields=['email_address'], name='idx_email_addr'),
        ),
        migrations.AddIndex(
            model_name='phonerisk',
            index=models.Index(fields=['phone_number'], name='idx_phone_num'),
        ),
        migrations.AddIndex(
            model_name='phonerisk',
            index=models.Index(fields=['risk_score'], name='idx_phone_risk'),
        ),
        migrations.AddIndex(
            model_name='scamreport',
            index=models.Index(fields=['risk_score'], name='idx_scam_score'),
        ),
        migrations.AddIndex(
            model_name='scamreport',
            index=models.Index(fields=['report_type'], name='idx_scam_type'),
        ),
        migrations.AddIndex(
            model_name='scamreport',
            index=models.Index(fields=['date_reported'], name='idx_scam_date'),
        ),
        migrations.AddIndex(
            model_name='scamreport',
            index=models.Index(fields=['user'], name='idx_scam_user'),
        ),
        migrations.AddIndex(
            model_name='scamreport',
            index=models.Index(fields=['company'], name='idx_scam_company'),
        ),
        migrations.AddIndex(
            model_name='takedownreport',
            index=models.Index(fields=['status'], name='idx_takedown_status'),
        ),
        migrations.AddIndex(
            model_name='takedownreport',
            index=models.Index(fields=['domain'], name='idx_takedown_domain'),
        ),
        migrations.AddIndex(
            model_name='urlrisk',
            index=models.Index(fields=['domain'], name='idx_url_domain'),
        ),
        migrations.AddIndex(
            model_name='urlrisk',
            index=models.Index(fields=['is_phishing'], name='idx_url_phish'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='idx_profile_role'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['company'], name='idx_profile_company'),
        ),
        migrations.AddIndex(
            model_name='whatsapprisk',
            index=models.Index(fields=['phone_number'], name='idx_wa_phone'),
        ),
    ]
