# Generated by Django 6.0.4 on 2026-06-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0012_alter_scamreport_report_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alert_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alert_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('INSTANT', 'Instant')], default='DAILY', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alert_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alert_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='takedown_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
